---
- name: Create a docker group
  group:
    name: "{{docker_group}}"
    state: present

- name: Add user(s) to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
    state: present
  with_items: "{{docker_users}}"
